adapters:
  - http
debug: false
enableVerify: true
verifyKey: INITKEYGEjUeHAb
singleMode: false
cacheSize: 4096
adapterSettings:
  http:
    host: localhost
    port: 8080
    cors: ['*']
  ws:
    host: localhost
    port: 8080
    reservedSyncId: -1
